locations:
  default_data_path: ./song_data/
  song_definitions: ./song_definitions/
  presets: ./effect_presets/
preferences:
  crossfade: 1/128
  overwrite: False
  main_preset_set:
  - swing
  - folk
  - waltz
  - seven
  - swapper
logging:
  level: DEBUG
  log_to_file: False
html_visualization:
  generate: False
  template_path: ./waveform_template.html.j2
  waveform_resolution: 400